{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:18.080Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:18.089Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:20.317Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:20.322Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:22.555Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:22.564Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:25.414Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:25.422Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:28.936Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:28.941Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:45.834Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:45.848Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:48.083Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:48.094Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:50.606Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:50.619Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:52.835Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:52.837Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:12:56.128Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:12:56.136Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:13:14.697Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:13:14.712Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:13:16.738Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:13:16.741Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:13:19.017Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:13:19.021Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:13:22.011Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:13:22.030Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T02:13:25.706Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T02:13:25.710Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:02.687Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:02.697Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:04.809Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:04.813Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:07.056Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:07.065Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:09.334Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:09.341Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:12.065Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:12.068Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:30.574Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:30.588Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:32.640Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:32.643Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:10:35.085Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:10:35.089Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:11:29.039Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:11:29.045Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:11:31.251Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:11:31.254Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:11:33.292Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:11:33.297Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:11:36.216Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:11:36.220Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T06:11:38.976Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T06:11:38.980Z"}
