{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-28T09:01:15.507Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-28T09:01:15.511Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"warn","timestamp":"2018-04-28T09:01:15.512Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-04-28T09:01:18.444Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-04-28T09:01:18.450Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-04-28T09:01:20.589Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-04-28T09:01:20.592Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-04-28T09:01:23.030Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:503:11)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:326:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (c:\\Work\\CoinKat\\server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-04-28T09:01:23.038Z"}
